import { Label } from "@/components/ui/label";

import type { Metadata } from "next";
import FormContent from "./form";

export const metadata: Metadata = {
  title: "Create New Paste and Share",
  description: "Generated by create next app",
};

const Paste = () => {
  return (
    <>
      <div className="max-w-7xl mx-auto px-8 pt-8">
        <div className="flex flex-row gap-8">
          <div className="w-full">
            <div className="mb-4">
              <div className="mb-2">
                <Label htmlFor="paste" className="text-xl">
                  Create new paste
                </Label>
              </div>

              <FormContent />
            </div>
          </div>

          <div className="w-[500px]">s</div>
        </div>
      </div>
    </>
  );
};

export default Paste;
